services:
  mysql:
    image: mysql:8.0
    container_name: educloud-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: educloud
      MYSQL_USER: edu
      MYSQL_PASSWORD: edu123456
      TZ: Asia/Shanghai
    ports:
      - "23306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_general_ci"
    ]
