services:
  mysql:
    image: mysql:8.0
    container_name: educloud-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: educloud
      MYSQL_USER: edu
      MYSQL_PASSWORD: edu123456
      TZ: Asia/Shanghai
    ports:
      - "23306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_general_ci"
    ]

  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.2
    container_name: xxl-job-admin
    restart: always
    ports:
      - "28080:8080"
    environment:
      # 这里写你的 mysql 地址（如果 mysql 也在 compose 里，用服务名 mysql）
      PARAMS: "--server.port=8080 --spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=root123456 --spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver --xxl.job.accessToken=educloud-token-123 --spring.mail.host="
    depends_on:
      - mysql

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: educloud-rabbitmq
    restart: unless-stopped
    ports:
      - "25672:5672"    # AMQP
      - "25673:15672"   # 管理后台
    environment:
      RABBITMQ_DEFAULT_USER: edu
      RABBITMQ_DEFAULT_PASS: edu123456
      TZ: Asia/Shanghai