server:
  port: 20003

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:23306/educloud?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: edu
    password: edu123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    openfeign:
          client:
            config:
              default:
                connectTimeout: 3000
                readTimeout: 3000

mybatis:
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:20010/eureka/

xxl:
  job:
    admin:
      addresses: http://localhost:28080/xxl-job-admin
    accessToken: educloud-token-123
    executor:
      appname: order-service-executor
      address: ""
      ip: ""
      port: 9999
      logpath: ./logs/xxl-job
      logretentiondays: 30

order:
  expire-minutes: 15